baseURL = 'https://education.launchcode.org/technical-analyst-curriculum/'
languageCode = 'en-us'
title = 'Technical Analysis Course'
theme = "hugo-theme-relearn"


[params]
themeVariant = ['lc-light', 'lc-dark-blue', 'lc-dark-blue-two']
